### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jinmeng-e** [Jinmeng-e/taja#15]
- [x] #23
- [x] #17

    - 속지 타입(이미지, 색상) - 2시간.
- [x] #18
- [x] #19

- [x] 4. 페이지 지우기 - 1시간 반
- [ ] 5. 겹쳐쓰기 펼쳐쓰기 - 이틀
- [x] 6. 형광펜 - 3 ~ 8
- [ ] 7. 종료 팝업 등.

**Comment by Jinmeng-e** [comment]
TODO
- [x] 타자 입력기를 통한 타자 입력.
- [ ] 페이지 넘기기 + 자동넘김
- [x] 오타 표시.
- [x] 좌 메뉴. 유저 상태 업데이트

넘어야할 난관
- Newline 중복 처리 안됨.
- 다음페이지 진행
- 겹치고 펼치기
- 형광펜
- api 작업
- ...
